apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: postman
  name: postman
  labels:
    app: postman
spec:
  selector:
    matchLabels:
      app: postman
  template:
    metadata:
      labels:
        app: postman
        name: postman
    spec:
      containers:
        - name: postman
          image: unnagirirao/Automation_Testing/postman
          imagePullPolicy: Always
        
          env:
            - name: SERVICE_NAME
              value: "go-app"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "localhost:4317"
            - name: INSECURE_MODE
              value: "true"
        
          ports:
        
        
          - containerPort: 5678
            name: http
        
        
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
        